import obPlugin from "@aidenlx/esbuild-plugin-obsidian";
import { build } from "esbuild";
import { lessLoader } from "esbuild-plugin-less";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source visit the plugins github repository
*/
`;

const isProd = process.env.BUILD === "production";

const cmModules = [
  "@codemirror/autocomplete",
  "@codemirror/closebrackets",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/comment",
  "@codemirror/fold",
  "@codemirror/gutter",
  "@codemirror/highlight",
  "@codemirror/history",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/matchbrackets",
  "@codemirror/panel",
  "@codemirror/rangeset",
  "@codemirror/rectangular-selection",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/stream-parser",
  "@codemirror/text",
  "@codemirror/tooltip",
  "@codemirror/view",
];
import { promises } from "fs";
const { readFile } = promises;

/**
 * @type {import("esbuild").Plugin}
 */
const patchVidPlayer = {
  name: "obsidian-plugin",
  setup: (build) => {
    build.onLoad(
      { filter: /vid-player-src\/src\/.+\.ts$/ },
      async ({ path }) => {
        let code = await readFile(path, "utf8");
        code = code.replace(/__DEV__/g, isProd ? "false" : "true");
        return { contents: code, loader: "ts" };
      },
    );
  },
};

try {
  await build({
    entryPoints: ["src/mx-main.ts"],
    bundle: true,
    watch: !isProd,
    platform: "browser",
    external: ["obsidian", "https", ...cmModules],
    format: "cjs",
    mainFields: ["browser", "module", "main"],
    banner: { js: banner },
    sourcemap: isProd ? false : "inline",
    minify: isProd,
    define: {
      "process.env.NODE_ENV": JSON.stringify(process.env.BUILD),
    },
    outfile: "build/main.js",
    plugins: [lessLoader(), obPlugin(), patchVidPlayer],
  });
} catch (err) {
  console.error(err);
  process.exit(1);
}
